####
# Get All product
GET {{url}}/api/products

###
# Create new product
POST {{url}}/api/products/
Content-Type: application/json

{
    "name": "Iphone 5",
    "price": 12000000,
    "categoryId": 1
}

####
# Get product by id
GET {{url}}/api/products/18

####
# Update product by id
PATCH {{url}}/api/products/2
Content-Type: application/json

{
    "name": "Mangkok Jagoo",
    "price": 90000,
    "categoryId": 1
}

####
# Delete product by id
DELETE {{url}}/api/products/18
